"""
Simple test script for GraphML export functionality.

Creates a basic graph with stratigraphic nodes and edges, then exports to GraphML.
"""

from s3dgraphy.graph import Graph
from s3dgraphy.nodes.stratigraphic_node import StratigraphicUnit
from s3dgraphy.nodes.document_node import DocumentNode
from s3dgraphy.nodes.extractor_node import ExtractorNode
from s3dgraphy.nodes.property_node import PropertyNode
from s3dgraphy.edges.edge import Edge
from s3dgraphy.exporter.graphml import GraphMLExporter
import uuid


def create_test_graph():
    """Create a simple test graph with stratigraphic nodes."""
    graph = Graph(graph_id=str(uuid.uuid4()), name={"en": "Test Graph"})

    # Create stratigraphic nodes with provenance information
    us01 = StratigraphicUnit(
        node_id=str(uuid.uuid4()),
        name="USM01",
        description="Foundation layer"
    )
    us01.node_type = "US"
    us01.extractor = "GPT-4"
    us01.document = "Report_2023.pdf"

    us02 = StratigraphicUnit(
        node_id=str(uuid.uuid4()),
        name="USM02",
        description="Wall structure"
    )
    us02.node_type = "US"
    us02.extractor = "GPT-4"
    us02.document = "Report_2023.pdf"

    us03 = StratigraphicUnit(
        node_id=str(uuid.uuid4()),
        name="USM03",
        description="Floor surface"
    )
    us03.node_type = "US"
    us03.extractor = "Claude"
    us03.document = "Field_notes_Day5.pdf"

    # Add nodes to graph
    graph.add_node(us01)
    graph.add_node(us02)
    graph.add_node(us03)

    # Add edges to graph (temporal relations)
    # USM03 is after USM02 (floor is more recent than wall)
    graph.add_edge(
        edge_id=str(uuid.uuid4()),
        edge_source=us03.node_id,
        edge_target=us02.node_id,
        edge_type="is_after"
    )

    # USM02 is after USM01 (wall is more recent than foundation)
    graph.add_edge(
        edge_id=str(uuid.uuid4()),
        edge_source=us02.node_id,
        edge_target=us01.node_id,
        edge_type="is_after"
    )

    # Paradata structure will be auto-generated by ParadataGenerator
    # based on extractor/document attributes

    return graph


def main():
    """Run the test."""
    print("="*60)
    print("GraphML Export Test with Paradata")
    print("="*60)

    # Create test graph
    print("\n1. Creating test graph...")
    graph = create_test_graph()
    print(f"   ✓ Graph created")
    print(f"     - Stratigraphic nodes: {len([n for n in graph.nodes if isinstance(n, StratigraphicUnit)])}")
    print(f"     - Temporal edges: {len(graph.edges)}")

    # Show provenance info
    print("\n2. Provenance information:")
    for node in graph.nodes:
        if isinstance(node, StratigraphicUnit):
            extractor = getattr(node, 'extractor', None)
            document = getattr(node, 'document', None)
            if extractor or document:
                print(f"   {node.name}: Extractor={extractor}, Document={document}")

    # Export to GraphML
    print("\n3. Exporting to GraphML...")
    print("   (Paradata nodes will be auto-generated)")
    output_path = "/tmp/test_export.graphml"
    exporter = GraphMLExporter(graph)
    exporter.export(output_path)

    print(f"\n4. Success!")
    print(f"   GraphML file saved: {output_path}")
    print(f"\nYou can open this file in yEd to visualize the graph.")
    print("Expected structure:")
    print("  - 3 stratigraphic nodes (USM01, USM02, USM03)")
    print("  - 3 property nodes (stratigraphic_definition)")
    print("  - 2 extractor nodes (D.GPT-4, D.Claude)")
    print("  - 2 document nodes (Report_2023.pdf, Field_notes_Day5.pdf)")
    print("  - Provenance chains: US → Property → Extractor → Document")
    print("="*60)


if __name__ == "__main__":
    main()
