# Configuration file for the Sphinx documentation builder.
# s3dgraphy documentation configuration

import os
import sys
import datetime

# Add the project root and src to Python path
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath('../src'))

# -- Project information -----------------------------------------------------
project = 's3dgraphy'
copyright = f'2024-{datetime.datetime.now().year}, Emanuel Demetrescu'
author = 'Emanuel Demetrescu'

# Read version from pyproject.toml
version = '0.1.0'  # Will be updated dynamically
release = version

# -- General configuration ---------------------------------------------------
extensions = [
    # Core Sphinx extensions
    'sphinx.ext.autodoc',           # Auto-generate API docs
    'sphinx.ext.autosummary',       # Generate summaries
    'sphinx.ext.napoleon',          # Google/NumPy docstring style
    'sphinx.ext.viewcode',          # Add source code links
    'sphinx.ext.intersphinx',       # Cross-reference other docs
    'sphinx.ext.todo',              # TODO items
    'sphinx.ext.coverage',          # Documentation coverage
    'sphinx.ext.ifconfig',          # Conditional content
    
    # External extensions
    'myst_parser',                  # Markdown support
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------
html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'analytics_id': '',  # Google Analytics ID
    'analytics_anonymize_ip': False,
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'style_nav_header_background': '#2980B9',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom CSS
html_css_files = [
    'custom.css',
]

# -- Extension configuration -------------------------------------------------

# -- Options for autodoc ----------------------------------------------------
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'show-inheritance': True,
    'imported-members': True,
}

# -- Options for autosummary ------------------------------------------------
autosummary_generate = True
autosummary_generate_overwrite = False

# -- Options for napoleon ---------------------------------------------------
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True

# -- Options for intersphinx ------------------------------------------------
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'pandas': ('https://pandas.pydata.org/docs/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'networkx': ('https://networkx.org/documentation/stable/', None),
}

# -- Options for todo extension ---------------------------------------------
todo_include_todos = True

# -- Options for MyST parser -----------------------------------------------
myst_enable_extensions = [
    "deflist",
    "tasklist",
    "colon_fence",
]

# -- Custom configuration ---------------------------------------------------

# Master document (index file)
master_doc = 'index'

# Source file suffixes
source_suffix = {
    '.rst': None,
    '.md': 'myst_parser',
}

# Language for content autogenerated by Sphinx
language = 'en'

# HTML context for templates
html_context = {
    'display_github': True,
    'github_user': 'zalmoxes-laran',
    'github_repo': 's3dgraphy',
    'github_version': 'main',
    'conf_py_path': '/docs/',
}

# Show last updated timestamp
html_last_updated_fmt = '%b %d, %Y'

def setup(app):
    """Custom setup function for additional configuration."""
    app.add_css_file('custom.css')
